services:
  jellyfin-discovery:
    image: ghcr.io/jamesmoore/jellyfin-discovery-shim:main
    network_mode: host
    restart: unless-stopped
    environment:
      JELLYFIN_ADDRESS: "https://jellyfin.$DOMAIN" # set the $DOMAIN environment variable in your shell or .env file
